api/WeworkDashboard/Wework.controller.js, api/WeworkDashboard/Wework.router.js, api/WeworkDashboard/Wework.service.js
=> First Push

api/complaint_master/complaintRegist.service.js
=> changes in complaint managent

api/WeWork/WeWork.controller.js, api/WeWork/WeWork.service.js, api/employee/employee.controller.js
=> console cleared

api/cm_directcomplaintRegister/directcmReg.service.js, api/complaint_master/complaintRegist.service.js, api/employee/employee.controller.js, api/employee/employee.service.js
=> Complaint management changes

api/cm_directcomplaintRegister/directcmReg.service.js, api/dietextraorder/extraorder.controller.js, api/dietextraorder/extraorder.router.js, api/dietextraorder/extrorder.sevice.js
Complaint management location added
=> Complaint management location added

api/dietextraorder/extraorder.controller.js, api/dietextraorder/extraorder.router.js, api/dietextraorder/extrorder.sevice.js
Diet Extra Oder view and update Completed
=> Diet Extra Oder view and update Completed

api/dietextraorder/extrorder.sevice.js, api/dietmenusettingdetail/dietmenudetl.controller.js, api/dietmenusettingdetail/dietmenudetl.router.js, api/dietmenusettingdetail/dietmenudetl.service.js, api/module_master/moduleMaster.service.js, api/user_group_right/groupRight.service.js, api/usergroup/usergroup.service.js, validation/validation_schema.js
Diet Modifications and Dashboard we work
=> Diet Modifications and Dashboard we work

api/WeEmpMapping/WeEMpMapping.controller.js, api/WeEmpMapping/WeEmpMapping.router.js, api/WeEmpMapping/WeEmpMapping.service.js, api/WeWork/WeWork.controller.js, api/WeWork/WeWork.router.js, api/WeWork/WeWork.service.js, app.js, validation/validation_schema.js
We work changes in discharge event page
=> We work changes in discharge event page

api/HighAntiBioticMaster/HighAntiBiotic.controll.js, api/WeWork/WeWork.controller.js, api/WeWork/WeWork.router.js, api/WeWork/WeWork.service.js, api/co_nursestation/nursestation.service.js, validation/validation_schema.js
wework patient List change,bhrc list changed
=> wework patient List change,bhrc list changed

api/commoncode/common.service.js, api/complaint_dashboard/cmDashboard.service.js, api/diet_dashboard/diet_dashboard.controller.js, api/diet_dashboard/diet_dashboard.router.js, api/diet_dashboard/diet_dashboard.service.js, api/employee/employee.controller.js, api/employee/employee.service.js, app.js
=> Diet DAshboard completed

api/WeWork/WeWork.controller.js, api/WeWork/WeWork.router.js, api/WeWork/WeWork.service.js
wework bed transfer modification,inpatient list changed
=> wework bed transfer modification,inpatient list changed

api/WeEmpMapping/WeEMpMapping.controller.js, api/WeEmpMapping/WeEmpMapping.router.js, api/WeEmpMapping/WeEmpMapping.service.js
wework employee floor selection changed
=> wework employee floor selection changed

api/hrm_data_get/data_get_insert.controller.js, api/hrm_data_get/data_get_insert.router.js, api/hrm_data_get/data_get_insert_service.js
hrm authorization import from hr
=> hrm authorization import from hr

api/WeWork/WeWork.controller.js, api/WeWork/WeWork.router.js, api/WeWork/WeWork.service.js
discharge status changed,bed transfer modification
=> discharge status changed,bed transfer modification

api/co_escalationmapping/escalationmapping.controller.js, api/co_escalationmapping/escalationmapping.router.js, api/co_escalationmapping/escalationmapping.service.js, api/co_escalationtimemast/escalationtime.controller.js, api/co_escalationtimemast/escalationtime.router.js, api/co_escalationtimemast/escalationtime.service.js, api/complaint_dashboard/cmDashboard.service.js, api/employee/employee.service.js, api/rm_roomcreation/roomcreation.service.js, api/time_escalation/timeescalation.controller.js, api/time_escalation/timeescalation.router.js, api/time_escalation/timeescalation.service.js, api/time_escalation2/time_esclvl2.controller.js, api/time_escalation2/time_esclvl2.router.js, api/time_escalation2/time_esclvl2.service.js, api/time_escalation3/time_esclvl3.controller.js, api/time_escalation3/time_esclvl3.router.js, api/time_escalation3/time_esclvl3.service.js, api/time_escalation4/time_esclvl4.controller.js, api/time_escalation4/time_esclvl4.router.js, api/time_escalation4/time_esclvl4.service.js, api/time_escalationToplvl/time_esctop.controller.js, api/time_escalationToplvl/time_esctop.router.js, api/time_escalationToplvl/time_esctop.service.js, app.js, validation/validation_schema.js
Time escalation pages for level1,level 2,level3, level 4 and top level
=> Time escalation pages for level1,level 2,level3, level 4 and top level

api/complaint_assign/complaintAssign.service.js, api/complaint_master/complaintRegist.router.js, api/crm_request_register/requestRegister.controller.js, api/crm_request_register/requestRegister.router.js, api/crm_request_register/requestRegister.service.js, api/employee/employee.controller.js, api/employee/employee.service.js, app.js, validation/validation_schema.js
Employee dept add to login details
=> Employee dept add to login details

api/crm_request_register/requestRegister.controller.js, api/crm_request_register/requestRegister.router.js, api/crm_request_register/requestRegister.service.js, api/employee/employee.controller.js, api/hrm_data_get/data_get_insert.controller.js, api/hrm_data_get/data_get_insert_service.js, app.js, validation/validation_schema.js
data insert from hrm tables to meliora api modification
=> data insert from hrm tables to meliora api modification

api/commoncode/common.controller.js, api/commoncode/common.router.js, api/commoncode/common.service.js, api/crm_request_register/requestRegister.controller.js, api/crm_request_register/requestRegister.service.js, api/employee/employee.controller.js, api/employee/employee.service.js, validation/validation_schema.js
User creation updating for resolve problem of data import from HR to meliora
=> User creation updating for resolve problem of data import from HR to meliora

api/complaint_assign/complaintAssign.controller.js, api/complaint_assign/complaintAssign.router.js, api/complaint_assign/complaintAssign.service.js
=> Transfer Department

api/complaint_assign/complaintAssign.controller.js, api/complaint_assign/complaintAssign.router.js, api/complaint_assign/complaintAssign.service.js
complaint remark changes in detail assign
=> complaint remark changes in detail assign

api/complaint_assign/complaintAssign.service.js
rectify_ holding_ remarks,verify_remarks,cm_rectify_status added
=> rectify_ holding_ remarks,verify_remarks,cm_rectify_status added

api/Rectifycomplit/Rectifycomplit.controller.js, api/Rectifycomplit/Rectifycomplit.router.js, api/Rectifycomplit/Rectifycomplit.service.js
rectify complaint changed into one Api
=> rectify complaint changed into one Api

api/Rectifycomplit/Rectifycomplit.service.js, api/hall_booking/hallBooking.controller.js, api/hall_booking/hallBooking.router.js, api/hall_booking/hallBooking.service.js, app.js
Hall booking and updations in complaint managemnt rectify
=> Hall booking and updations in complaint managemnt rectify

api/commoncode/common.controller.js, api/commoncode/common.router.js, api/commoncode/common.service.js, api/complaint_assign/complaintAssign.controller.js, api/complaint_assign/complaintAssign.service.js, api/crm_request_register/requestRegister.controller.js, api/crm_request_register/requestRegister.router.js, api/crm_request_register/requestRegister.service.js, api/diet_process_mast/dietprocess.controller.js, api/diet_process_mast/dietprocess.service.js, api/dietmenusettingdetail/dietmenudetl.controller.js, api/dietmenusettingdetail/dietmenudetl.router.js, api/dietmenusettingdetail/dietmenudetl.service.js, api/hrm_data_get/data_get_insert.controller.js, api/hrm_data_get/data_get_insert_service.js, validation/validation_schema.js
Request management first push and modification in diet
=> Request management first push and modification in diet

api/co_nursestation/nursestation.service.js, api/commoncode/common.controller.js, api/crm_request_register/requestRegister.service.js, api/diet_process_mast/dietprocess.service.js, api/diet_report/diet_report.service.js, api/dietextraorder/extrorder.sevice.js, api/dietmenusettingdetail/dietmenudetl.service.js, api/ndrf_request/ndrfrequest.controller.js, api/ndrf_request/ndrfrequest.router.js, api/ndrf_request/ndrfrequest.service.js, app.js, validation/validation_schema.js
Diet Modification and Request management modifications
=> Diet Modification and Request management modifications

api/HallMaster/HallMaster.service.js, api/HallMaster/Hallmaster.controller.js, api/HallMaster/Hallmaster.router.js, api/commoncode/common.controller.js, api/hall_booking/hallBooking.controller.js, api/hall_booking/hallBooking.router.js, api/hall_booking/hallBooking.service.js, app.js
hall booking, deprtment approval, we work modifiocation
=> hall booking, deprtment approval, we work modifiocation

api/hall_booking/hallBooking.service.js
=> hall booking modification

api/crm_request_register/requestRegister.service.js, api/diet_delivery_mark/deliverymark.service.js, api/diet_process_mast/dietprocess.controller.js, api/ndrf_request/ndrfrequest.controller.js, api/ndrf_request/ndrfrequest.router.js, api/ndrf_request/ndrfrequest.service.js
Diet modifications in diet menu settings and request management changes
=> Diet modifications in diet menu settings and request management changes

api/fileupload/fileupload.controller.js, api/fileupload/fileupload.router.js, api/fileupload/fileupload.service.js, api/ndrf_request/ndrfrequest.controller.js, api/ndrf_request/ndrfrequest.router.js, api/ndrf_request/ndrfrequest.service.js, app.js
"Request Management,NDRF Completed"
=> Request Management,NDRF Completed

api/Rectifycomplit/Rectifycomplit.controller.js, api/commoncode/common.controller.js, api/commoncode/common.router.js, api/commoncode/common.service.js, api/complaint_master/complaintRegist.service.js, socketio/socketUltil.js
After install socket first push
=> After install socket first push

api/WeEmpMapping/WeEMpMapping.controller.js, api/WeEmpMapping/WeEmpMapping.service.js, api/WeWork/WeWork.service.js, api/WeworkDashboard/Wework.service.js
dashboard total patient count changed
=> dashboard total patient count changed

api/complaint_hic/complaintHic.controller.js, api/complaint_hic/complaintHic.router.js, api/complaint_hic/complaintHic.service.js, app.js
=> hic correction

api/crm_request_register/requestRegister.controller.js, api/crm_request_register/requestRegister.service.js, api/ndrf_request/ndrfrequest.service.js
Request Management model Design Corrected
=> Request Management model Design Corrected

api/om_emp_mapping/omEmpMap.router.js, api/om_emp_mapping/omEmpMap.service.js, api/om_emp_mapping/omEmpMapp.controller.js, api/om_table_mast/omTableMast.controller.js, api/om_table_mast/omTableMast.router.js, api/om_table_mast/omTableMast.service.js, app.js, validation/validation_schema.js
Om Table creation and employee mapping Masters
=> Om Table creation and employee mapping Masters

api/commoncode/common.controller.js, api/commoncode/common.router.js, api/commoncode/common.service.js
=> Manual Display

api/Rectifycomplit/Rectifycomplit.service.js, api/cm_directcomplaintRegister/directcmReg.service.js, api/cm_prority_mst/cm_priority.controller.js, api/cm_prority_mst/cm_priority.router.js, api/cm_prority_mst/cm_priority_service.js, api/com_emp_mapping/com_emp_mapping.controller.js, api/com_emp_mapping/com_emp_mapping.router.js, api/com_emp_mapping/com_emp_mapping.service.js, api/complaint_assign/complaintAssign.controller.js, api/complaint_assign/complaintAssign.router.js, api/complaint_assign/complaintAssign.service.js, api/complaint_master/complaintRegist.service.js, api/employee/employee.service.js, app.js, validation/validation_schema.js
Dept transfer remark,emp transfer and priority level are completed
=> Dept transfer remark,emp transfer and priority level are completed

api/Rectifycomplit/Rectifycomplit.service.js, api/cm_directcomplaintRegister/directcmReg.controller.js, api/cm_directcomplaintRegister/directcmReg.service.js, api/commoncode/common.controller.js, api/commoncode/common.router.js, api/commoncode/common.service.js, api/complaint_master/complaintRegist.controller.js, api/complaint_master/complaintRegist.service.js, api/employee/employee.controller.js, api/employee/employee.service.js, api/hrm_data_get/data_get_insert.controller.js, api/hrm_data_get/data_get_insert.router.js, api/hrm_data_get/data_get_insert_service.js, api/ndrf_request/ndrfrequest.controller.js, validation/validation_schema.js
Changes in Complaint registration page, data transfer hr, and rectify complaint
=> Changes in Complaint registration page, data transfer hr, and rectify complaint

api/complaint_assign/complaintAssign.controller.js, api/complaint_assign/complaintAssign.router.js, api/complaint_assign/complaintAssign.service.js, api/complaint_master/complaintRegist.service.js, api/employee/employee.service.js
Supervisor List Add verification and Assist Transfer, Report for dept wise, registred complaint menu"
=> Supervisor List Add verification and Assist Transfer, Report for dept wise, registred complaint menu"

api/com_emp_mapping/com_emp_mapping.controller.js, api/com_emp_mapping/com_emp_mapping.router.js, api/com_emp_mapping/com_emp_mapping.service.js, api/complaint_assign/complaintAssign.service.js
In user creation Supervisor select added
=> In user creation Supervisor select added

api/cm_complaint_mobapp/cmmobapp.controller.js, api/cm_complaint_mobapp/cmmobapp.router.js, api/cm_complaint_mobapp/cmmobapp.service.js, api/co_departmentmaster/department.service.js, api/commoncode/common.controller.js, api/commoncode/common.router.js, api/commoncode/common.service.js, api/crm_request_register/requestRegister.controller.js, api/crm_request_register/requestRegister.router.js, api/crm_request_register/requestRegister.service.js, api/ndrf_request/ndrfrequest.service.js, validation/validation_schema.js
CRF modifications based on first meeting and Api for complaint management mobile app
=> CRF modifications based on first meeting and Api for complaint management mobile app

api/rm_dashboard/dashboard.controller.js, api/rm_dashboard/dashboard.router.js, api/rm_dashboard/dashboard.services.js, app.js
=> Dashboard for Room management

api/crm_request_register/requestRegister.controller.js, api/crm_request_register/requestRegister.router.js, api/crm_request_register/requestRegister.service.js, api/rm_floor_creation/rm_floor.services.js, api/rm_roomnew_creation/rm_newroom.controller.js, api/rm_roomnew_creation/rm_newroom.services.js, api/rm_selectCompnents/select.controller.js, api/rm_selectCompnents/select.router.js, api/rm_selectCompnents/select.services.js
Floor and Room Creation,Crf Modification based on second Meeting
=> Floor and Room Creation,Crf Modification based on second Meeting

api/crm_request_register/requestRegister.controller.js, api/crm_request_register/requestRegister.router.js, api/crm_request_register/requestRegister.service.js
=> CRF modifications

api/rm_dashboard/dashboard.controller.js, api/rm_floor_creation/rm_floor.controller.js, api/rm_floor_creation/rm_floor.services.js, api/rm_roomnew_creation/rm_newroom.controller.js, api/rm_roomnew_creation/rm_newroom.router.js, api/rm_roomnew_creation/rm_newroom.services.js
Room management partially completed
=> Room management partially completed

api/am_item_name_creation/item.controller.js, api/am_item_name_creation/item.router.js, api/am_item_name_creation/item.services.js, api/am_primary_custodian/primary.controller.js, api/am_primary_custodian/primary.router.js, api/am_primary_custodian/primary.services.js, api/am_secondary_custodian/secondary.controller.js, api/am_secondary_custodian/secondary.router.js, api/am_secondary_custodian/secondary.services.js, api/am_selectcomponents/select.controller.js, api/am_selectcomponents/select.router.js, api/am_selectcomponents/select.services.js, api/am_sub_group/sub_group.services.js, api/am_subcategory/am_subcategory.services.js, api/rm_dashboard/dashboard.controller.js, api/rm_dashboard/dashboard.services.js, api/rm_roomnew_creation/rm_newroom.controller.js, api/rm_roomnew_creation/rm_newroom.services.js, app.js
=> Room Management completed

api/rm_roomnew_creation/rm_newroom.services.js, api/rm_selectCompnents/select.controller.js, api/rm_selectCompnents/select.router.js, api/rm_selectCompnents/select.services.js
=> Room Management modifications

api/cm_complaint_mobapp/cmmobapp.router.js, api/cm_complaint_mobapp/cmmobapp.service.js, api/cm_prority_mst/cm_priority.controller.js, api/cm_prority_mst/cm_priority_service.js, api/cms_reports/cms_report.controller.js, api/cms_reports/cms_report.router.js, api/cms_reports/cms_report.service.js, api/complaint_master/complaintRegist.service.js, validation/validation_schema.js
Complaint management corrections
=> Complaint management corrections

api/cm_complaint_mobapp/cmmobapp.service.js
Complaint management Mobile app Api correction
=> Complaint management Mobile app Api correction

api/complaint_assign/complaintAssign.controller.js, api/employee/employee.controller.js, api/employee/employee.router.js, api/employee/employee.service.js
=> Password change option added

api/am_item_name_creation/item.services.js, api/am_model/model.contoller.js, api/am_model/model.router.js, api/am_model/model.services.js, api/am_selectcomponents/select.controller.js, api/am_selectcomponents/select.router.js, api/am_selectcomponents/select.services.js, api/am_submodel/submodel.controller.js, api/am_submodel/submodel.services.js, api/am_submodel/sumodel.router.js, api/am_uom/uom.controller.js, api/am_uom/uom.router.js, api/am_uom/uom.services.js, app.js
model,submodel master creation and item creation design
=> model,submodel master creation and item creation design

api/am_item_name_creation/item.services.js
=> Item Creation Design

api/am_model/model.contoller.js, api/fileupload/fileupload.controller.js, api/fileupload/fileupload.router.js, package-lock.json, package.json
File upload and compress file in model master
=> File upload and compress file in model master

api/am_asset_type/am_assetType.services.js, api/am_asset_type/am_asset_type.controller.js, api/complaint_assign/complaintAssign.service.js, validation/validation_schema.js
Complaint Assign Service Query Update on Assist list
=> Complaint Assign Service Query Update on Assist list

api/cm_directcomplaintRegister/directcmReg.controller.js, api/complaint_master/complaintRegist.controller.js
Complaint Registration Slno Auto generation updates"
=> Complaint Registration Slno Auto generation updates"

api/cm_prority_mst/cm_priority_service.js, api/complaint_assign/complaintAssign.service.js, api/employee/employee.controller.js, api/employee/employee.service.js
User Creation error solved and verify supervisor model updated
=> User Creation error solved and verify supervisor model updated

api/cm_complaint_mobapp/cmmobapp.service.js, api/cms_reports/cms_report.controller.js, api/cms_reports/cms_report.router.js, api/cms_reports/cms_report.service.js, api/complaint_assign/complaintAssign.controller.js
=> Updations In cms reports

api/am_asset_type/am_assetType.services.js, api/am_asset_type/am_asset_type.controller.js, api/am_category/am_category.controller.js, api/am_category/am_category.services.js, api/am_group/am_group.controller.js, api/am_group/am_group.services.js, api/am_item_name_creation/item.controller.js, api/am_item_name_creation/item.services.js, api/am_item_type/item_type.controller.js, api/am_item_type/item_type.services.js, api/am_manufacture/manufacture.controller.js, api/am_manufacture/manufacture.services.js, api/am_model/model.contoller.js, api/am_model/model.services.js, api/am_primary_custodian/primary.services.js, api/am_secondary_custodian/secondary.services.js, api/am_sub_group/sub_group.controller.js, api/am_sub_group/sub_group.services.js, api/am_subcategory/am_subcategory.controller.js, api/am_subcategory/am_subcategory.services.js, api/am_submodel/submodel.controller.js, api/am_submodel/submodel.services.js, api/am_uom/uom.controller.js, api/am_uom/uom.services.js, api/fileupload/fileupload.controller.js, api/fileupload/fileupload.router.js, validation/validation_schema.js
AM Module Select Components changes to Autocomplete and add modal add in Item creation page
=> AM Module Select Components changes to Autocomplete and add modal add in Item creation page

api/am_Item_creation_mast/item_creation_mast.controller.js, api/am_Item_creation_mast/item_creation_mast.router.js, api/am_Item_creation_mast/item_creation_mast.service.js, api/am_item_name_creation/item.controller.js, api/am_item_name_creation/item.router.js, api/am_item_name_creation/item.services.js, api/am_selectcomponents/select.controller.js, api/am_selectcomponents/select.router.js, api/am_selectcomponents/select.services.js, api/cm_complaint_mobapp/cmmobapp.service.js, app.js
Asset Management Item Creation Completed For Live
=> Asset Management Item Creation Completed For Live

api/am_Item_creation_mast/item_creation_mast.controller.js, api/am_Item_creation_mast/item_creation_mast.router.js, api/am_Item_creation_mast/item_creation_mast.service.js, api/am_custodian_department/am_custodian_dept.controller.js, api/am_custodian_department/am_custodian_dept.router.js, api/am_custodian_department/am_custodian_dept.services.js, api/am_item_name_creation/item.controller.js, api/am_item_name_creation/item.services.js, api/am_selectcomponents/select.controller.js, api/am_selectcomponents/select.router.js, api/am_selectcomponents/select.services.js, api/rm_roomnew_creation/rm_newroom.services.js, app.js
Asset Name creation, item creation and and listing completed and QR code print
=> Asset Name creation, item creation and and listing completed and QR code print

api/am_Item_creation_mast/item_creation_mast.controller.js, api/am_Item_creation_mast/item_creation_mast.service.js, api/am_item_creation_detail/am_itemdetail.controller.js, api/am_item_creation_detail/am_itemdetail.router.js, api/am_item_creation_detail/am_itemdetail.service.js, app.js
=> Corrections in asset For Live

api/am_Item_creation_mast/item_creation_mast.service.js, api/am_item_creation_detail/am_itemdetail.controller.js, api/am_item_creation_detail/am_itemdetail.router.js, api/am_item_creation_detail/am_itemdetail.service.js, api/fileupload/fileupload.controller.js, api/fileupload/fileupload.router.js, api/fileupload/fileupload.service.js
Item details Added In Asset Manangement"
=> Item details Added In Asset Manangement

api/am_item_name_creation/item.services.js, api/it_wifi_management/wifi.controller.js, api/it_wifi_management/wifi.router.js, api/it_wifi_management/wifi.services.js, api/rm_room_category_master/room_category.controller.js
=> Wifi management completed

api/am_category/am_category.controller.js, api/it_backup_detailsmast/backupDetails.controller.js, api/it_backup_detailsmast/backupDetails.router.js, api/it_backup_detailsmast/backupDetails.service.js, api/it_backup_verification/backupVerification.controller.js, api/it_backup_verification/backupVerification.router.js, api/it_backup_verification/backupVerification.service.js, api/it_backupdashboard/backupdash.controller.js, api/it_backupdashboard/backupdash.router.js, api/it_backupdashboard/backupdash.service.js, api/it_scheduletimemast/scheduletimemast.controller.js, api/it_scheduletimemast/scheduletimemast.router.js, api/it_scheduletimemast/scheduletimemast.service.js, api/it_scheduletypemast/scheduletype.controller.js, api/it_scheduletypemast/scheduletype.router.js, api/it_scheduletypemast/scheduletype.service.js, app.js, validation/validation_schema.js
Backup details fot It mangement
=> Backup details fot It mangement

api/it_backup_detailsmast/backupDetails.service.js, api/it_backup_verification/backupVerification.service.js, api/it_backupdashboard/backupdash.controller.js, api/it_backupdashboard/backupdash.service.js, api/it_password_device_type/password_devicetype.service.js, api/it_scheduletimemast/scheduletimemast.service.js, api/it_scheduletypemast/scheduletype.service.js
=> Dashboard modification

api/it_password_credential_type_master/password_credential.controller.js, api/it_password_credential_type_master/password_credential.router.js, api/it_password_credential_type_master/password_credential.service.js, api/it_password_device_type/password_devicetype.router.js, api/it_password_management/password_management.controller.js, api/it_password_management/password_management.router.js, api/it_password_management/password_management.service.js, api/it_select_components/devicetypeSelect.controller.js, api/it_select_components/devicetypeSelect.router.js, api/it_select_components/devicetypeSelect.service.js, api/it_tarrif/tarriffDetails.Controller.js, api/it_tarrif/tarriffDetails.router.js, api/it_tarrif/tarriffDetails.service.js, app.js
=> Password management Completed

api/am_Item_creation_mast/item_creation_mast.controller.js, api/am_Item_creation_mast/item_creation_mast.service.js, api/am_item_name_creation/item.controller.js, api/am_item_name_creation/item.router.js, api/am_item_name_creation/item.services.js
Correction in asset creation and opening entry
=> Correction in asset creation and opening entry

api/am_Item_creation_mast/item_creation_mast.controller.js, api/am_Item_creation_mast/item_creation_mast.service.js, api/am_custodian_department/am_custodian_dept.services.js, api/am_item_creation_detail/am_itemdetail.controller.js, api/am_item_creation_detail/am_itemdetail.router.js, api/am_item_creation_detail/am_itemdetail.service.js, api/am_selectcomponents/select.controller.js, api/am_selectcomponents/select.router.js, api/am_selectcomponents/select.services.js, api/complaint_assign/complaintAssign.service.js, api/rm_dashboard/dashboard.controller.js, api/rm_dashboard/dashboard.router.js, api/rm_dashboard/dashboard.services.js
Room Management Modification and sub room creation completed
=> Room Management Modification and sub room creation completed

api/crm_request_register/requestRegister.controller.js, api/crm_request_register/requestRegister.service.js
=> CRF Live Changes Until ms

api/crf_fileupload/crf_fileupload.controller.js, api/crm_request_register/requestRegister.controller.js, api/crm_request_register/requestRegister.router.js, api/crm_request_register/requestRegister.service.js, api/ndrf_request/ndrfrequest.controller.js, api/ndrf_request/ndrfrequest.router.js, api/ndrf_request/ndrfrequest.service.js, api/rm_newsubroom_mast/rm_newsubroom_mast.service.js
=> Crf For live

api/am_item_creation_detail/am_itemdetail.controller.js, api/am_item_creation_detail/am_itemdetail.router.js, api/am_item_creation_detail/am_itemdetail.service.js, api/crf_dashboards/crfdashboard.controller.js, api/crf_dashboards/crfdashboard.router.js, api/crf_dashboards/crfdashboard.service.js, api/ndrf_request/ndrfrequest.controller.js, api/ndrf_request/ndrfrequest.router.js, api/ndrf_request/ndrfrequest.service.js, app.js
=> Asset Updations

api/crm_request_register/requestRegister.service.js
Image not showing problem solved
=> Image not showing problem solved

api/crf_dashboards/crfdashboard.service.js, api/crf_fileupload/crf_fileupload.controller.js, api/crm_request_register/requestRegister.service.js
=> CRF Live ERror Correction

.gitignore, api/crm_request_register/requestRegister.service.js
=> Changes in DMS view list

api/hrm_data_get/data_get_insert.controller.js, api/hrm_data_get/data_get_insert.router.js, api/hrm_data_get/data_get_insert_service.js
HRMS data Transfer department and sections
=> HRMS data Transfer department and sections

validation/validation_schema.js
Validation min strength changes to 1
=> Validation min strength changes to 1

api/tm_task_file_upload/task_file_upload.controller.js, api/tm_task_file_upload/task_file_upload.router.js, api/tm_task_file_upload/task_file_upload.service.js, api/tm_task_management/taskmanagement.service.js, api/tm_task_views/tmview.service.js
Image upload corrections in task management
=> Image upload corrections in task management

api/am_Item_creation_mast/item_creation_mast.service.js, api/am_asset_dept_transfer/asset_depttransfer.service.js, api/am_asset_internaltrans/asset_internaltrans.controller.js, api/am_asset_internaltrans/asset_internaltrans.router.js, api/am_asset_internaltrans/asset_internaltrans.service.js, api/crm_emergncytype_mast/emergency_type.controller.js, api/crm_emergncytype_mast/emergncy_tpe.router.js, api/crm_emergncytype_mast/emergncy_type.service.js, api/rm_dashboard/dashboard.services.js, app.js, validation/validation_schema.js
=> In Asset Transfer Room Added

api/tm_task_management/taskmanagement.controller.js, api/tm_task_management/taskmanagement.router.js, api/tm_task_management/taskmanagement.service.js, api/tm_task_views/tmview.controller.js, api/tm_task_views/tmview.router.js, api/tm_task_views/tmview.service.js
In task management changes are completed for live
=> In task management changes are completed for live

api/co_deptsectionmaster/deptsection.service.js, api/commoncode/common.service.js, api/crm_emergncytype_mast/emergency_type.controller.js, api/crm_emergncytype_mast/emergncy_tpe.router.js, api/crm_emergncytype_mast/emergncy_type.service.js, api/crm_new_file_upload/crm_fileupload.controller.js, api/crm_new_file_upload/crm_fileupload.router.js, api/crm_new_file_upload/crm_fileupload.service.js, api/crm_newrequest_registration/newRequestRegister.controller.js, api/crm_newrequest_registration/newRequestRegister.router.js, api/crm_newrequest_registration/newRequestRegister.service.js, api/hrm_data_get/data_get_insert.controller.js, api/hrm_data_get/data_get_insert.router.js, api/hrm_data_get/data_get_insert_service.js, app.js, validation/validation_schema.js
designation, branch and salutation new table created for Meliora
=> designation, branch and salutation new table created for Meliora

api/tm_reports/tmreports.controller.js, api/tm_reports/tmreports.router.js, api/tm_reports/tmreports.service.js, api/tm_task_management/taskmanagement.controller.js, api/tm_task_management/taskmanagement.router.js, api/tm_task_management/taskmanagement.service.js, api/tm_task_views/tmview.controller.js, api/tm_task_views/tmview.router.js, api/tm_task_views/tmview.service.js, app.js
Corrections in Task management
=> Corrections in Task management

api/tm_task_management/taskmanagement.service.js, api/tm_task_views/tmview.controller.js, api/tm_task_views/tmview.router.js, api/tm_task_views/tmview.service.js
Task management updation for live
=> Task management updation for live

api/it_backup_detailsmast/backupDetails.controller.js, api/it_backup_detailsmast/backupDetails.router.js, api/it_backup_detailsmast/backupDetails.service.js, api/qi_dailydetailsEmergency/qi_emergency.controller.js, api/qi_dailydetailsEmergency/qi_emergency.router.js, api/qi_dailydetailsEmergency/qi_emergency.service.js, api/qi_dailydetailsEndoscopy/qi_daily.controller.js, api/qi_dailydetailsEndoscopy/qi_daily.router.js, api/qi_dailydetailsEndoscopy/qi_daily.service.js, api/qi_departmentmast/qidepartment.controller.js, api/qi_departmentmast/qidepartment.router.js, api/qi_departmentmast/qidepartment.service.js, api/qi_master/qltyIndicator.controller.js, api/qi_master/qltyIndicator.router.js, api/qi_master/qltyIndicator.service.js, app.js, validation/validation_schema.js
=> backup modification

api/tm_task_management/taskmanagement.service.js, api/tm_task_views/tmview.service.js
=> Task management for live

api/co_deptsectionmaster/deptsection.service.js, api/crm_emergncytype_mast/emergncy_type.service.js, api/crm_newrequest_registration/newRequestRegister.controller.js, api/crm_newrequest_registration/newRequestRegister.router.js, api/crm_newrequest_registration/newRequestRegister.service.js, api/crm_req_approval/crmreq_approval.controller.js, api/crm_req_approval/crmreq_approval.router.js, api/crm_req_approval/crmreq_approval.service.js, app.js
Initial stage of pushing crf new module
=> Initial stage of pushing crf new module

api/crf_fileupload/crf_fileupload.controller.js, api/crm_emergncytype_mast/emergncy_type.service.js, api/crm_new_file_upload/crm_fileupload.controller.js, api/crm_new_file_upload/crm_fileupload.router.js, api/crm_new_file_upload/crm_fileupload.service.js, api/crm_new_purchase/crm_purchase.controller.js, api/crm_new_purchase/crm_purchase.router.js, api/crm_new_purchase/crm_purchase.service.js, api/crm_newrequest_registration/newRequestRegister.controller.js, api/crm_newrequest_registration/newRequestRegister.router.js, api/crm_newrequest_registration/newRequestRegister.service.js, api/crm_req_approval/crmreq_approval.controller.js, api/crm_req_approval/crmreq_approval.router.js, api/crm_req_approval/crmreq_approval.service.js, app.js
=> Crf phase 2 for first level

api/crm_new_purchase/crm_purchase.controller.js, api/crm_new_purchase/crm_purchase.router.js, api/crm_new_purchase/crm_purchase.service.js, api/crm_newrequest_registration/newRequestRegister.controller.js, api/crm_newrequest_registration/newRequestRegister.router.js, api/crm_newrequest_registration/newRequestRegister.service.js, validation/validation_schema.js
=> CRF Phase 2 for live

api/qi_daily_census/daily_census.controller.js, api/qi_daily_census/daily_census.router.js, api/qi_daily_census/daily_census.service.js, api/qicensusnursing_mast/census_nursing.controller.js
Adding HIS data for daily census and its including in pdf view
=> Adding HIS data for daily census and its including in pdf view

api/qi_daily_census/daily_census.controller.js, api/qi_daily_census/daily_census.service.js
changes in HIS inpateint list, design changes in  data entering
=> changes in HIS inpateint list, design changes in  data entering

api/crm_newrequest_registration/newRequestRegister.service.js, api/crm_req_approval/crmreq_approval.controller.js, api/crm_req_approval/crmreq_approval.router.js, api/crm_req_approval/crmreq_approval.service.js
Correction in new item add and user acknowledgement
=> Correction in new item add and user acknowledgement

api/qi_daily_census/daily_census.controller.js, api/qi_daily_census/daily_census.router.js, api/qi_daily_census/daily_census.service.js
modification to View and Save DAMA and LAMA patient Count and Update HIS data
=> modification to View and Save DAMA and LAMA patient Count and Update HIS data

api/qi_dailydetailsEndoscopy/qi_daily.controller.js, api/qi_dailydetailsEndoscopy/qi_daily.router.js, api/qi_dailydetailsEndoscopy/qi_daily.service.js, api/qi_dept_mast/qi_dept.controller.js, api/qi_dept_mast/qi_dept.router.js, api/qi_dept_mast/qi_dept.service.js, api/qicensusnursing_mast/census_nursing.service.js, app.js, validation/validation_schema.js
nursing station view in ascending order and get endoscopy patient list for qi
=> nursing station view in ascending order and get endoscopy patient list for qi

api/crm_new_file_upload/crm_fileupload.controller.js, api/crm_new_file_upload/crm_fileupload.router.js, api/crm_new_file_upload/crm_fileupload.service.js, api/crm_new_purchase/crm_purchase.service.js, api/crm_newrequest_registration/newRequestRegister.service.js, api/crm_req_approval/crmreq_approval.controller.js, api/crm_req_approval/crmreq_approval.router.js, api/crm_req_approval/crmreq_approval.service.js
CRF every approval page image upload added and also completed for Live
=> CRF every approval page image upload added and also completed for Live

api/crm_new_purchase/crm_purchase.service.js, api/crm_newrequest_registration/newRequestRegister.service.js
error solve when live data insert to new CRF
=> error solve when live data insert to new CRF

api/crm_new_purchase/crm_purchase.controller.js, api/crm_new_purchase/crm_purchase.service.js, api/crm_newrequest_registration/newRequestRegister.service.js
Add Backdrop in all table list
=> Add Backdrop in all table list

api/co_deptsectionmaster/deptsection.controller.js
Color change in Reject,onhold and ed&md only show gm approved"
=> Color change in Reject,onhold and ed&md only show gm approved"

api/crm_newrequest_registration/newRequestRegister.service.js
Reject and on hold button click list shows, Craft Type added
=> Reject and onhold button click list shows, Crf Type added

api/cm_complaintype/complainttype.service.js, api/crm_new_purchase/crm_purchase.service.js
Purchase page adding new options separate for ack pending,quat pending,po close and po to supplier
=> Purchase page adding new options separate for ack pending,quat pending,po close and po to supplier 

api/crm_new_purchase/crm_purchase.controller.js, api/crm_new_purchase/crm_purchase.router.js, api/crm_new_purchase/crm_purchase.service.js
In purchase Page Yesterdays Lived facing issues, solve that issue
=> In purchase Page Yesterdays Lived facing issues, solve that issue

api/crm_new_approvals/newReqApprovalsList.controller.js, api/crm_new_approvals/newReqApprovalsList.router.js, api/crm_new_approvals/newReqApprovalsList.service.js, api/crm_new_file_upload/crm_fileupload.controller.js, api/crm_new_purchase/crm_purchase.service.js, app.js
In store menu list query correction
=> In store menu list query correction

api/crm_new_approvals/newReqApprovalsList.controller.js, api/crm_new_approvals/newReqApprovalsList.router.js, api/crm_new_approvals/newReqApprovalsList.service.js, api/crm_new_purchase/crm_purchase.service.js
Separate api for pending,allist and close
=> Separate api for pending,allist and close 

api/am_item_name_creation/item.services.js
In asset name creation page item type showing wrong this problem solved
=> In asset name creation page item type showing wrong this problem solved

api/it_bill_management/bill.controller.js, api/it_bill_management/bill.router.js, api/it_bill_management/bill.service.js, api/it_bill_supplier_detail_master/supp_detail.service.js, api/it_managemnt_file_upload/it_file_upload.controller.js, api/tm_task_management/taskmanagement.controller.js, api/tm_task_management/taskmanagement.router.js, api/tm_task_management/taskmanagement.service.js
Bill management updations in dashboard
=> Bill management updations in dashboard

api/commoncode/common.controller.js, api/crm_request_register/requestRegister.service.js
Dashborad issue solved for KMC
=> Dashborad issue solved for KMC

api/am_Item_creation_mast/item_creation_mast.service.js, api/am_file_upload/am_fileupload.controller.js, api/am_file_upload/am_fileupload.router.js, api/am_file_upload/am_fileupload.service.js, api/am_item_creation_detail/am_itemdetail.controller.js, api/am_item_creation_detail/am_itemdetail.router.js, api/am_item_creation_detail/am_itemdetail.service.js, app.js
In asset module add bill, amc/cmc details with image
=> In asset module add bill, amc/cmc details with image

api/qi_dailydetailsEmergency/qi_emergency.controller.js, api/qi_dailydetailsEmergency/qi_emergency.router.js, api/qi_dailydetailsEmergency/qi_emergency.service.js, api/qi_dailydetailsEndoscopy/qi_daily.router.js, api/qi_dailydetailsEndoscopy/qi_daily.service.js
Endoscopy quality indicator corrections for Live
=> Endoscopy quality indicator corrections for Live

api/am_Item_creation_mast/item_creation_mast.controller.js, api/am_Item_creation_mast/item_creation_mast.router.js, api/am_Item_creation_mast/item_creation_mast.service.js, api/am_item_creation_detail/am_itemdetail.service.js, api/crm_new_approvals/newReqApprovalsList.service.js
in Asset Management Bill amount enter separately and also search by serial no"
=> in Asset Management Bill amount enter separately and also search by serial no"

api/incident_mast/incident.controller.js, api/qi_dailydetailsEndoscopy/qi_daily.controller.js, api/qi_dailydetailsEndoscopy/qi_daily.router.js, api/qi_dailydetailsEndoscopy/qi_daily.service.js, api/qi_equipment_mast/equipment.controller.js, api/qi_equipment_mast/equipment.router.js, api/qi_equipment_mast/equipment.service.js, app.js, validation/validation_schema.js
In Quality indicator query change in daily report view
=> In Quality indicator query change in daily report view

api/am_item_creation_detail/am_itemdetail.service.js, api/crm_req_approval/crmreq_approval.controller.js
Add bill option enable in asset details add
=> Add bill option enable in asset details add

api/am_Item_creation_mast/item_creation_mast.service.js, api/am_item_creation_detail/am_itemdetail.service.js
In asset opening entry remove dept ,deptsec, room, subroom selection
=> In asset opening entry remove dept ,deptsec, room, subroom selection

api/am_Item_creation_mast/item_creation_mast.controller.js, api/am_Item_creation_mast/item_creation_mast.router.js, api/am_Item_creation_mast/item_creation_mast.service.js, api/am_custodian_department/am_custodian_dept.controller.js, api/am_custodian_department/am_custodian_dept.router.js, api/am_custodian_department/am_custodian_dept.services.js, api/am_item_creation_detail/am_itemdetail.controller.js, api/am_item_creation_detail/am_itemdetail.router.js, api/am_item_creation_detail/am_itemdetail.service.js, api/employee/employee.controller.js, api/employee/employee.service.js
Spare transfer to condemnation and service page done
=> Spare transfer to condemnation and service page done

api/crm_req_approval/crmreq_approval.service.js, api/hrm_data_get/data_get_insert_service.js
Changes in data transfer from hr
=> Changes in data transfer from hr

api/am_rack_master/am_rack.service.js, api/crm_new_approvals/newReqApprovalsList.controller.js, api/crm_new_approvals/newReqApprovalsList.router.js, api/crm_new_approvals/newReqApprovalsList.service.js, api/crm_reports/crm_report.controller.js, api/crm_reports/crm_report.service.js, api/crm_reports/crm_reports.router.js, app.js, validation/validation_schema.js
In CRF Reject and hold list sort by months"
=> In CRF Reject and hold list sort by months

api/tm_all_dept_task/tmalldept.controller.js, api/tm_all_dept_task/tmalldept.router.js, api/tm_all_dept_task/tmalldept.service.js, api/tm_dropdowns/tm_list.controller.js, api/tm_dropdowns/tm_list.router.js, api/tm_dropdowns/tm_list.service.js, api/tm_task_management/taskmanagement.controller.js, api/tm_task_management/taskmanagement.router.js, api/tm_task_management/taskmanagement.service.js, api/tm_task_views/tmview.controller.js, api/tm_task_views/tmview.router.js, api/tm_task_views/tmview.service.js, app.js
In task management directors desk menu, task acceptance menu completed for Live
=> In task management directors desk menu, task acceptance menu completed for Live

api/incident_mast/incident.controller.js, api/incident_mast/incident.router.js, api/incident_mast/incident.service.js, api/qi_dailydetailsEndoscopy/qi_daily.controller.js, api/qi_dailydetailsEndoscopy/qi_daily.router.js, api/qi_dailydetailsEndoscopy/qi_daily.service.js, api/qi_detailsIP/qi_ip.controller.js, api/qi_detailsIP/qi_ip.router.js, api/qi_detailsIP/qi_ip.service.js, api/qi_equipment_mast/equipment.controller.js, api/qi_equipment_mast/equipment.router.js, api/qi_equipment_mast/equipment.service.js, app.js, validation/validation_schema.js
In quality indicator in endoscopy inpatient module completed for live
=> In quality indicator in endoscopy inpatient module completed for live

api/Rectifycomplit/Rectifycomplit.controller.js, api/Rectifycomplit/Rectifycomplit.service.js, api/complaint_assign/complaintAssign.controller.js, api/complaint_assign/complaintAssign.service.js, api/crm_new_purchase/crm_purchase.service.js, api/crm_reports/crm_report.controller.js, api/crm_reports/crm_report.service.js, api/crm_reports/crm_reports.router.js, api/employee/employee.controller.js
In CRF Purchase ED sign Added And userAcked Crf Report completed
=> In CRF Purchase ED sign Added And userAcked Crf Report completed

api/qi_dailydetailsEndoscopy/qi_daily.controller.js, api/qi_dailydetailsEndoscopy/qi_daily.router.js, api/qi_dailydetailsEndoscopy/qi_daily.service.js
Employee select remove in Qi page
=> Employee select remove in Qi page

api/am_item_creation_detail/am_itemdetail.controller.js, api/am_item_creation_detail/am_itemdetail.service.js, api/crm_reports/crm_report.controller.js, api/crm_reports/crm_report.service.js, api/crm_reports/crm_reports.router.js, api/crm_req_approval/crmreq_approval.service.js
CRF approval correction in HOD Approval"
=> CRF approval correction in HOD Approval

api/crm_reports/crm_report.controller.js, api/crm_reports/crm_report.service.js, api/crm_reports/crm_reports.router.js, api/hrm_data_get/data_get_insert.controller.js
Full Crf flow based  report on particular CRF no  completed
=> Full Crf flow based  report on particular CRF no  completed

api/qi_dailydetailsEndoscopy/qi_daily.controller.js, api/qi_dailydetailsEndoscopy/qi_daily.router.js, api/qi_dailydetailsEndoscopy/qi_daily.service.js, api/qi_initial_assessment_details/assessment.controller.js, api/qi_initial_assessment_details/assessment.router.js, api/qi_initial_assessment_details/assessment_service.js, app.js
Op waiting time report generation
=> Op waiting time report generation

api/it_bill_management/bill.controller.js, api/it_bill_management/bill.router.js, api/it_bill_management/bill.service.js, api/tm_all_dept_task/tmalldept.controller.js, api/tm_all_dept_task/tmalldept.router.js, api/tm_all_dept_task/tmalldept.service.js, api/tm_graph_charts/tm_graph.controller.js, api/tm_graph_charts/tm_graph.router.js, api/tm_graph_charts/tm_graph.service.js, api/tm_task_management/taskmanagement.router.js, api/tm_task_management/taskmanagement.service.js, api/tm_task_views/tmview.controller.js, api/tm_task_views/tmview.router.js, api/tm_task_views/tmview.service.js, app.js
Employee Performance Sheet and Slide
=> Employee Performance Sheet and Slide

api/Rectifycomplit/Rectifycomplit.controller.js, api/Rectifycomplit/Rectifycomplit.router.js, api/Rectifycomplit/Rectifycomplit.service.js, api/am_spare_condemnation/am_spare_condemnation.controller.js, api/am_spare_condemnation/am_spare_condemnation.router.js, api/am_spare_condemnation/am_spare_condemnation.service.js, api/crm_reports/crm_report.controller.js, api/crm_reports/crm_report.service.js, api/crm_reports/crm_reports.router.js, app.js
Asset Add in rectification, condemnation and service list in Asset
=> Asset Add in rectification, condemnation and service list in Asset

api/it_bill_management/bill.controller.js, api/it_bill_management/bill.router.js, api/it_bill_management/bill.service.js, api/tm_graph_charts/tm_graph.controller.js, api/tm_graph_charts/tm_graph.router.js, api/tm_graph_charts/tm_graph.service.js
Task Management Sql Query correction
=> Task Management Sql Query correction

api/hrm_data_get/data_get_insert.controller.js, api/hrm_data_get/data_get_insert.router.js, api/hrm_data_get/data_get_insert_service.js
HR table data import to Meliora by menus
=> HR table data import to meliora by menus

api/it_bill_management/bill.controller.js, api/it_bill_management/bill.router.js, api/it_bill_management/bill.service.js, api/tm_graph_charts/tm_graph.service.js
Task Management Query error correction
=> Task Management Query error correction

api/am_Item_creation_mast/item_creation_mast.service.js, api/am_spare_condemnation/am_spare_condemnation.controller.js, api/am_spare_condemnation/am_spare_condemnation.router.js, api/am_spare_condemnation/am_spare_condemnation.service.js
Pm due date over list in asset
=> Pm due date over list in asset

api/am_reports/am_reports.service.js
asset department wise report only shows corresponding depts
=> asset department wise report only shows corresponding depts

api/qi_daily_census/daily_census.service.js, api/qi_dailydetailsDialysis/qi_dialysis.service.js, api/qi_dailydetailsEmergency/qi_emergency.service.js, api/qi_dailydetailsEndoscopy/qi_daily.service.js, api/qi_detailsIP/qi_ip.service.js, api/qi_initial_assessment_details/assessment_service.js
Query Modification (date formate)
=> Query Modification (date formate)

api/tm_all_dept_task/tmalldept.service.js, api/tm_dropdowns/tm_list.controller.js, api/tm_dropdowns/tm_list.router.js, api/tm_dropdowns/tm_list.service.js
Task Management code correction duedate,project,performance sheet
=> Task Management code correction duedate,project,performance sheet

api/it_wifi_management/wifi.controller.js, api/it_wifi_management/wifi.router.js, api/it_wifi_management/wifi.services.js
wifi qr code expiry correction, renwal
=> wifi qr code expiry correction, renwal

api/it_bill_management/bill.service.js
itBillManagement Added bill Active Status
=> itBillManagement Added bill Active Status

api/am_custodian_department/am_custodian_dept.services.js
=> Meliora api ajiminsha

api/it_wifi_management/wifi.controller.js, api/it_wifi_management/wifi.router.js, api/it_wifi_management/wifi.services.js
wifi code generation modification
=> wifi code generation modification

api/cms_reports/cms_report.service.js
Modification in complaint category Report
=> Modification in complaint category Report

api/am_reports/am_reorts.controller.js, api/am_reports/am_reports.router.js, api/am_reports/am_reports.service.js
Item Count Included In Asset Item Report
=> Item Count Included In Asset Item Report

api/employee/employee.controller.js, api/med_vallet/med_vallet.controller.js, api/med_vallet/med_vallet.router.js, api/med_vallet/med_vallet.service.js, api/mv_vehicle_registration/mv_vehicle.controller.js, api/mv_vehicle_registration/mv_vehicle.router.js, api/mv_vehicle_registration/mv_vehicle.service.js, api/mv_vehicle_registration/uploadFiles.js, api/tm_task_file_upload/task_file_upload.controller.js, app.js, authentication/ValidationCheck.js
=> Cleared all log statemenst

api/mv_vehicle_registration/mv_vehicle.controller.js, api/mv_vehicle_registration/uploadFiles.js, app.js
=> Multer upload Completed

api/it_backup_detailsmast/backupDetails.controller.js, api/it_backup_detailsmast/backupDetails.router.js, api/it_backup_detailsmast/backupDetails.service.js, api/it_backup_type_master/backup_type.controller.js, api/it_backup_type_master/backup_type.router.js, api/it_backup_type_master/backup_type.service.js, api/it_backup_verification/backupVerification.controller.js, api/it_backup_verification/backupVerification.router.js, api/it_backup_verification/backupVerification.service.js, api/it_backupdashboard/backupdash.controller.js, api/it_backupdashboard/backupdash.router.js, api/it_backupdashboard/backupdash.service.js, api/it_bill_management/bill.service.js, api/it_communication_device_details/communication.services.js, api/it_sim_operators/sim_operators.controller.js, api/it_sim_operators/sim_operators.router.js, api/it_sim_operators/sim_operators_service.js, app.js, validation/validation_schema.js
Master creation for It Backup and Sim Operators
=> Master creation for It Backup and Sim Operators

api/it_backup_verification/backupVerification.service.js, api/it_backupdashboard/backupdash.controller.js, api/it_backupdashboard/backupdash.service.js, validation/validation_schema.js
=> Added Backup Folder Path

api/am_item_creation_detail/am_itemdetail.service.js, api/it_backupdashboard/backupdash.service.js
Multiple Warranty and Guarantee for item in Asset Management
=> Multiple Warranty and Guarantee for item in Asset Management 

api/employee/employee.controller.js, api/employee/employee.service.js, api/it_password_management/password_management.service.js
Asset Dashboard and Employee login Designation
=> Meliora ajmi cmp

api/crm_newrequest_registration/newRequestRegister.service.js, api/crm_req_approval/crmreq_approval.controller.js
approval page error correction
=> approval page error correction

api/am_spare_condemnation/am_spare_condemnation.controller.js, api/complaint_assign/complaintAssign.controller.js, api/complaint_assign/complaintAssign.router.js, api/complaint_assign/complaintAssign.service.js
Ticket management,Pending tickets count and assist request Count
=> Ticket management,Pending tickets count and assist request Count

api/crm_new_purchase/crm_purchase.controller.js, api/crm_new_purchase/crm_purchase.router.js, api/crm_new_purchase/crm_purchase.service.js, api/crm_newrequest_registration/newRequestRegister.controller.js, api/crm_newrequest_registration/newRequestRegister.router.js, api/crm_newrequest_registration/newRequestRegister.service.js
=> work order

api/crm_newrequest_registration/newRequestRegister.controller.js, api/crm_newrequest_registration/newRequestRegister.router.js, api/crm_newrequest_registration/newRequestRegister.service.js
=> ms and dms approval

api/crm_req_approval/crmreq_approval.controller.js
=> Meliora amal api

api/crm_req_approval/crmreq_approval.controller.js, api/crm_req_approval/crmreq_approval.router.js, api/crm_req_approval/crmreq_approval.service.js, app.js, package-lock.json
=> md approval

api/crm_newrequest_registration/newRequestRegister.controller.js
=> dms approval querry changes

api/Feedback/Feedback.controller.js, api/Feedback/Feedback.router.js, api/Feedback/Feedback.service.js, api/tokenValidation/tokenValidation.js, app.js
Cleared Conflict and Chnaged api
=> Cleared Conflict and Chnaged api

api/Feedback/Feedback.service.js, app.js
Feedback Service Inpatient GetQuery Changed
=> Feedback Service Inpatient GetQuery Changed

api/Feedback/Feedback.controller.js, api/Feedback/Feedback.router.js, api/Feedback/Feedback.service.js, app.js
Insertion and updation of Doctor name in the IPADMISS table
=> Insertion and updation of Doctor name in the IPADMISS table

api/Feedback/Feedback.router.js, api/Feedback/Feedback.service.js
=> Doctor Name inserting

api/co_inchhod_authriztn/inchhod_authoriztn.controller.js, api/co_inchhod_authriztn/inchhod_authoriztn.router.js, api/co_inchhod_authriztn/inchod_authoriztn.service.js, api/crm_new_purchase/crm_purchase.service.js, api/crm_newrequest_registration/newRequestRegister.controller.js, api/crm_newrequest_registration/newRequestRegister.router.js, api/crm_newrequest_registration/newRequestRegister.service.js, api/crm_req_approval/crmreq_approval.controller.js, api/crm_req_approval/crmreq_approval.router.js, api/crm_req_approval/crmreq_approval.service.js, app.js
=> kmc data collection

api/Feedback/Feedback.controller.js, api/Feedback/Feedback.router.js, api/Feedback/Feedback.service.js, app.js
Changed Database Name form Queries
=> Changed Database Name form Queries

api/Feedback/Feedback.controller.js, api/Feedback/Feedback.router.js, api/Feedback/Feedback.service.js, app.js
Error Corrected Meliora Backend Feedback
=> Error Corrected Meliora Backend Feedback

api/crm_new_file_upload/crm_fileupload.controller.js, api/crm_new_file_upload/crm_fileupload.router.js, api/crm_new_file_upload/crm_fileupload.service.js, api/qi_daily_census/daily_census.controller.js, api/qi_daily_census/daily_census.router.js, api/qi_daily_census/daily_census.service.js, app.js, package-lock.json, package.json
=> report and delivery marking

api/notificationMenu/notification.controller.js, api/notificationMenu/notification.router.js, api/notificationMenu/notification.service.js
=> get Active Notifications

api/crm_new_file_upload/crm_fileupload.controller.js, api/crm_new_file_upload/crm_fileupload.router.js, app.js
=> get nabh files
